# Generated by Django 6.1.1 on 2026-09-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="facing_direction",
            field=models.CharField(
                choices=[
                    ("north", "North"),
                    ("south", "South"),
                    ("east", "East"),
                    ("west", "West"),
                    ("northeast", "Northeast"),
                    ("northwest", "Northwest"),
                    ("southeast", "Southeast"),
                    ("southwest", "Southwest"),
                ],
                default="north",
                max_length=70,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="parking_spaces",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="year_built",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
